### ISSUE TITLE
got repeated id

### ISSUE THREAD

**Issue by njnuwjq** [bwmarrin/snowflake#9] opened 2017-07-27 02:55 UTC
hi, 

i've tested with my laptop on window7, call the function test_id in example for several times,

	test_id()
//	time.Sleep(1)
	test_id()
//	time.Sleep(1)
	test_id()
//	time.Sleep(1)
	test_id()
//	time.Sleep(1)
	test_id()
//	time.Sleep(1)

and got 
======log==============
Int64  ID: 890399407000784896
String ID: 890399407000784896
Base2  ID: 110001011011010101011000101100001010100000000001000000000000
Base64 ID: ODkwMzk5NDA3MDAwNzg0ODk2
ID Time  : 1501122736107
ID Node  : 1
ID Step  : 0
ID       : 890399407000784897
Int64  ID: 890399407000784896
String ID: 890399407000784896
Base2  ID: 110001011011010101011000101100001010100000000001000000000000
Base64 ID: ODkwMzk5NDA3MDAwNzg0ODk2
ID Time  : 1501122736107
ID Node  : 1
ID Step  : 0
ID       : 890399407000784897
Int64  ID: 890399407000784896
String ID: 890399407000784896
Base2  ID: 110001011011010101011000101100001010100000000001000000000000
Base64 ID: ODkwMzk5NDA3MDAwNzg0ODk2
ID Time  : 1501122736107
ID Node  : 1
ID Step  : 0
ID       : 890399407000784897
Int64  ID: 890399407000784896
String ID: 890399407000784896
Base2  ID: 110001011011010101011000101100001010100000000001000000000000
Base64 ID: ODkwMzk5NDA3MDAwNzg0ODk2
ID Time  : 1501122736107
ID Node  : 1
ID Step  : 0
ID       : 890399407000784897
Int64  ID: 890399407000784896
String ID: 890399407000784896
Base2  ID: 110001011011010101011000101100001010100000000001000000000000
Base64 ID: ODkwMzk5NDA3MDAwNzg0ODk2
ID Time  : 1501122736107
ID Node  : 1
ID Step  : 0
ID       : 890399407000784897
===================

the id are the same~~~~~~~

calling with time delay, the id changed, 
	test_id()
	time.Sleep(1)
	test_id()
	time.Sleep(1)
	test_id()
	time.Sleep(1)
	test_id()
	time.Sleep(1)

seems the id isn't increased

**Comment by bwmarrin** [comment] 2017-07-31 21:17
Could you share with me an entire example app (should be small, I would guess) that recreates this problem so I can test it on my end?

**Comment by bwmarrin** [comment] 2018-02-01 00:31
Well, since I can't reproduce the problem and no further details provided.. I'm going to close this :)

**Comment by simi24** [comment] 2018-06-21 06:57
I also got repeated in my test:
```
import (
	"github.com/bwmarrin/snowflake"
)
func GetUUID() int64 {
	// Create a new Node with a Node number of 1
	node, err := snowflake.NewNode(1)
	if err != nil {
		panic("GetUUID error")
	}

	return int64(node.Generate())
}
```
and test func:
```
import (
	"testing"
)

func TestGetUUID(t *testing.T) {
	for i := 0; i < 1000; i++ {
		id := GetUUID()
		t.Log("id: ", id)
	}
}
```
test result:
```
......
uuid_test.go:11: id:  1009689810996039680
uuid_test.go:11: id:  1009689810996039680
uuid_test.go:11: id:  1009689810996039680
uuid_test.go:11: id:  1009689811000233984
uuid_test.go:11: id:  1009689811000233984
uuid_test.go:11: id:  1009689811000233984
uuid_test.go:11: id:  1009689811000233984
......
```

**Comment by bwmarrin** [comment] 2018-07-11 13:58
Thanks, I'll try testing with this code.

**Comment by bwmarrin** [comment] 2018-07-26 13:45
@simicn

Not sure why I didn't catch onto this initially.  But the example code you posted here is creating a new **node** instance on every single call.  So the **step** or snowflow ID sequence number is lost and reset to zero on every call.  This is why it's creating duplicates IDs.

When creating IDs the Twitter Snowflake uses a format of the current time, node ID, then a step or sequence number.  Every ID generated in the same millisecond must increment the step value.  Since this is essentially resetting that step value to zero every time - every ID generated in the same same millisecond will be a duplicate ID.

Taking a loot at https://github.com/bwmarrin/snowflake#how-it-works might be helpful to understand the format a little better.

**For you to ensure unique IDs, you must reuse the node instance instead of creating a new one on every single call.**

**Closed by bwmarrin** 2018-07-26 13:45 UTC

**Comment by bwmarrin** [comment] 2018-07-26 13:47
@njnuwjq I'm not sure if you're using the code in a similar way to the above example by @simicn but if you are, that might explain the issue you were having as well.  If you're doing something different and can provide a code example I'd love to look into it.

**Comment by simicn** [comment] 2018-07-27 07:15
I get it, thanks @bwmarrin .
